POST http://localhost:3000/user/signup 
Content-Type: application/json

{
    "name":"Sill",
    "role":"NORMAL",
    "email":"sill@sill",
    "password":"123456"
}

###

# @name login
POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email":"Larissa@Lanes",
    "password":"123456"
}

###

# @name registerBand
POST  http://localhost:3000/band/register 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMWJmYmMzLTM3YjYtNDAyMC04Y2IxLTFhMDUwMGYzYmMyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYwMjU0MSwiZXhwIjoxNjQ3NjAzNzQxfQ.H_YOWdvI_xhj4vrMBOonbOeHqJFEdJSZ0VHbD_Wj7nU

{
    "name":"gun in roses",
    "music_genre":"rock",
    "responsible": "Larissa"
 
}

###

GET  http://localhost:3000/band/info/:id
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMWJmYmMzLTM3YjYtNDAyMC04Y2IxLTFhMDUwMGYzYmMyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYxMDA1MCwiZXhwIjoxNjQ3NjExMjUwfQ.ZDg6kW-Os-fm5g8ud9x3q18O4tzu_aOONR7-zOhJvuk
Content-Type: application/json

{
    "name": "gun in roses"

}

###

POST http://localhost:3000/show/create
Content-Type: application/json

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMWJmYmMzLTM3YjYtNDAyMC04Y2IxLTFhMDUwMGYzYmMyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYwMjU0MSwiZXhwIjoxNjQ3NjAzNzQxfQ.H_YOWdvI_xhj4vrMBOonbOeHqJFEdJSZ0VHbD_Wj7nU

{
    "weekDay": "FRIDAY",
    "startTime": 10,
    "endTime": 20,
    "bandId": "99586356-e92a-4770-bb26-5b473630fe73"
 }



